'use client';
import Link from 'next/link';
import {X,ArrowUpRight} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {properties,money,type Property} from '@/lib/data';
import {useSite} from './site-shell';
import {PageHeading,EmptyState} from './listings';
const rows:[string,(p:Property)=>string][]=[['Fiyat',p=>money(p.price)+(p.transactionType==='Kiralık'?' / ay':'')],['İşlem türü',p=>p.transactionType],['Konum',p=>p.neighborhood],['Brüt / net m²',p=>`${p.grossArea} / ${p.netArea}`],['Oda',p=>p.rooms],['Kat',p=>p.floor],['Bina yaşı',p=>String(p.buildingAge)],['Isıtma',p=>p.heating],['Otopark',p=>p.parking?'Var':'Yok'],['Balkon',p=>p.balcony?'Var':'Yok']];
export function Comparison(){const{compare,toggleCompare}=useSite();const items=properties.filter(p=>compare.includes(p.id));return <main id="main" className="container comparison-page"><PageHeading eyebrow="PORTFÖY KARŞILAŞTIRMA" title="Yan yana, daha net." description="En fazla 3 portföyün detaylarını aynı yerde değerlendirin."/>{items.length===0?<EmptyState title="Karşılaştırmak için portföy seçin."><Link className="button" href="/satilik">Portföyleri keşfet <ArrowUpRight size={18}/></Link></EmptyState>:<><p className="demo-note">{items.length} / 3 portföy · Tüm bilgiler temsili demo verisidir.</p><div className="comparison-table"><Table><TableHeader><TableRow><TableHead>Gayrimenkul</TableHead>{items.map(p=><TableHead key={p.id}><div className="comparison-card"><button onClick={()=>toggleCompare(p.id)} aria-label={`${p.title} karşılaştırmadan çıkar`}><X size={18}/></button><img src={p.images[0]} alt={p.title+' temsili fotoğrafı'} width={400} height={270}/><Link href={`/ilan/${p.slug}`}>{p.title}<ArrowUpRight size={17}/></Link></div></TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(([label,get])=><TableRow key={label}><TableCell>{label}</TableCell>{items.map(p=><TableCell key={p.id}>{get(p)}</TableCell>)}</TableRow>)}</TableBody></Table></div>{items.length<3&&<Link className="button outline" href="/satilik">Bir portföy daha seç <ArrowUpRight size={18}/></Link>}</>}</main>}
