'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {createContext,useContext,useEffect,useState, type ReactNode} from 'react';
import {ArrowUpRight,Heart,Menu,X,Phone,MessageCircle,SlidersHorizontal,ArrowLeftRight,MapPin} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {companyInfo} from '@/lib/data';
type Store={favorites:string[];compare:string[];toggleFavorite:(id:string)=>void;toggleCompare:(id:string)=>void;notify:(s:string)=>void};
const Context=createContext<Store>({favorites:[],compare:[],toggleFavorite:()=>{},toggleCompare:()=>{},notify:()=>{}});
export const useSite=()=>useContext(Context);
export function SiteProvider({children}:{children:ReactNode}){
 const [favorites,setFavorites]=useState<string[]>([]),[compare,setCompare]=useState<string[]>([]),[ready,setReady]=useState(false),[notice,notify]=useState('');
 useEffect(()=>{try{const read=(key:string)=>{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'):[]};setFavorites(read('mavi-favorites'));setCompare(read('mavi-compare').slice(0,3));}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready){try{localStorage.setItem('mavi-favorites',JSON.stringify(favorites));localStorage.setItem('mavi-compare',JSON.stringify(compare))}catch{}}},[favorites,compare,ready]);
 useEffect(()=>{if(notice){const t=setTimeout(()=>notify(''),4500);return()=>clearTimeout(t)}},[notice]);
 return <Context.Provider value={{favorites,compare,toggleFavorite:id=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]),toggleCompare:id=>{if(compare.includes(id))setCompare(compare.filter(x=>x!==id));else if(compare.length<3)setCompare([...compare,id]);else notify('En fazla 3 ilan karşılaştırabilirsiniz. Önce seçtiğiniz bir ilanı kaldırın.');},notify}}>{children}{notice&&<div className="toast" role="status">{notice}<button aria-label="Bildirimi kapat" onClick={()=>notify('')}><X size={16}/></button></div>}{compare.length>0&&<div className="compare-bar"><ArrowLeftRight size={18}/><span>{compare.length}/3 portföy seçildi</span><Link href="/karsilastir">Karşılaştır <ArrowUpRight size={16}/></Link></div>}</Context.Provider>
}
const nav=[['Ana Sayfa','/'],['Satılık','/satilik'],['Kiralık','/kiralik'],['Projeler','/projeler'],['Bölgeler','/bolgeler'],['Danışmanlarımız','/danismanlar'],['Hakkımızda','/hakkimizda'],['İletişim','/iletisim']];
export function Logo(){return <Link href="/" className="logo" aria-label="Mavi Gayrimenkul ana sayfa"><span className="logo-mark">m<span>.</span></span><span className="logo-type">mavi<span>GAYRİMENKUL</span></span></Link>}
export function Header(){const [open,setOpen]=useState(false);const path=usePathname();const {favorites}=useSite();useEffect(()=>setOpen(false),[path]);return <><div className="topline"><span><MapPin size={12}/> Bolu’yu biliyoruz. Sizi dinliyoruz.</span><span>Bir MK Digital Systems demo çalışması <i/> BOLU, TÜRKİYE</span></div><header className="header"><Logo/><nav aria-label="Ana navigasyon">{nav.map(([title,url])=><Link className={path===url?'active':''} key={url} href={url}>{title}</Link>)}</nav><div className="header-actions"><Link className="icon-button favorite-nav" href="/favoriler" aria-label={`Favorilerim (${favorites.length})`}><Heart size={20}/>{favorites.length>0&&<small>{favorites.length}</small>}</Link><Link href="/degerleme" className="button small">Ücretsiz Değerleme <ArrowUpRight size={17}/></Link><button className="icon-button menu-button" aria-label="Menüyü aç" onClick={()=>setOpen(true)}><Menu/></button></div></header><Dialog open={open} onOpenChange={setOpen}><DialogContent className="mobile-menu modal"><DialogTitle>Keşfet</DialogTitle><DialogDescription className="sr-only">Mavi Gayrimenkul sayfaları</DialogDescription>{nav.map(([title,url])=><Link key={url} href={url} onClick={()=>setOpen(false)}>{title}<ArrowUpRight size={19}/></Link>)}<Link href="/favoriler" onClick={()=>setOpen(false)}>Favorilerim ({favorites.length})</Link><Link href="/portfoy-gonder" onClick={()=>setOpen(false)}>Portföyünü Gönder</Link></DialogContent></Dialog></>}
export function DemoContact({kind='WhatsApp',className='button outline'}:{kind?:string;className?:string}){const [open,setOpen]=useState(false);return <><button className={className} onClick={()=>setOpen(true)}>{kind==='WhatsApp'?<MessageCircle size={17}/>:<Phone size={17}/>} {kind}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="modal"><DialogTitle>{kind} ile iletişim</DialogTitle><DialogDescription>Bu bir portföy demosudur. Gerçek bir telefon veya WhatsApp hattına bağlı değildir. Danışmanlık talebi deneyimini iletişim formunda inceleyebilirsiniz.</DialogDescription><Link href="/iletisim" className="button" onClick={()=>setOpen(false)}>İletişim formuna git <ArrowUpRight size={18}/></Link></DialogContent></Dialog></>}
export function Footer(){return <><footer className="footer"><div className="footer-top"><div><Logo/><p>Doğru mülk. Doğru karar.<br/>Bolu’da yeni bir başlangıç.</p><span className="eyebrow">BOLU MERKEZ / BOLU</span></div><div><h3>Gayrimenkul</h3><Link href="/satilik">Satılık portföyler</Link><Link href="/kiralik">Kiralık portföyler</Link><Link href="/projeler">Projeler</Link><Link href="/bolgeler">Bölgeleri keşfet</Link></div><div><h3>Mavi’yi tanıyın</h3><Link href="/danismanlar">Danışmanlarımız</Link><Link href="/hakkimizda">Hakkımızda</Link><Link href="/yatirim-rehberi">Yatırım rehberi</Link><Link href="/iletisim">İletişim</Link></div><div><h3>Birlikte başlayalım</h3><Link href="/degerleme">Ücretsiz değerleme <ArrowUpRight size={15}/></Link><Link href="/portfoy-gonder">Portföyünü gönder <ArrowUpRight size={15}/></Link><DemoContact kind="Bizi arayın" className="text-button"/><DemoContact kind="Instagram · Demo" className="text-button"/></div></div><div className="footer-bottom"><p>© 2026 Mavi Gayrimenkul · {companyInfo.credit}</p><p>Demo site. Tüm ilanlar, kişiler ve yorumlar kurgusaldır. Fotoğraflar temsilidir.</p></div></footer><div className="mobile-actions"><DemoContact kind="Ara" className=""/><DemoContact className=""/><Link href="/satilik"><SlidersHorizontal size={18}/>İlanlar</Link><Link href="/degerleme"><ArrowUpRight size={18}/>Değerleme</Link></div></>}
