export const photo = (id:number,width=1000) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${width}`;
export const heroImage=photo(7598378,2000);
export const slugify=(s:string)=>s.toLocaleLowerCase('tr').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export const propertyTypes=['Daire','Villa','Müstakil Ev','Arsa','İş Yeri','Dükkan','Ofis','Tarla'];
export const locations=['Bolu Merkez','Karacasu','Kalıcı Konutlar','Bahçelievler','Borazanlar','Tabaklar','Sağlık','Gölyüzü','Köroğlu','Karaçayır','Gerede','Mengen','Mudurnu','Göynük','Yeniçağa','Dörtdivan'];
export interface Property {id:string;slug:string;title:string;transactionType:'Satılık'|'Kiralık';propertyType:string;price:number;currency:string;city:string;district:string;neighborhood:string;address:string;grossArea:number;netArea:number;rooms:string;buildingAge:number;floor:string;totalFloors:number;heating:string;bathrooms:number;balcony:boolean;parking:boolean;elevator:boolean;furnished:boolean;creditEligible:boolean;inComplex:boolean;latitude:number;longitude:number;description:string;features:string[];images:string[];advisorId:string;featured:boolean;createdAt:string;status:string;isDemo:true}
const seeds:[string,string,string,number,number,string,number][]=[
 ['Bahçelievler’de ışıkla buluşan yaşam','Bahçelievler','Daire',4850000,165,'3+1',11296222],
 ['Karacasu’da doğayla iç içe villa','Karacasu','Villa',12750000,285,'4+1',7587877],
 ['Kalıcı Konutlar’da ferah bir başlangıç','Kalıcı Konutlar','Daire',24500,115,'2+1',7534563],
 ['Bolu Merkez’de modern 3+1 daire','Bolu Merkez','Daire',4250000,150,'3+1',15251055],
 ['Borazanlar’da şehrin içinde sakinlik','Borazanlar','Daire',3950000,135,'3+1',19889118],
 ['Mudurnu’da bahçeli müstakil yaşam','Mudurnu','Müstakil Ev',6800000,210,'4+1',26812642],
 ['Gölyüzü’nde aydınlık köşe daire','Gölyüzü','Daire',3250000,105,'2+1',8082228],
 ['Tabaklar’da merkezi konumda daire','Tabaklar','Daire',2900000,95,'2+1',28853337],
 ['Sağlık’ta balkonlu aile dairesi','Sağlık','Daire',3600000,140,'3+1',12029111],
 ['Karaçayır’da parka komşu daire','Karaçayır','Daire',5150000,175,'4+1',7598364],
 ['Gerede’de yeni yaşam alanınız','Gerede','Daire',2350000,100,'2+1',37140648],
 ['Köroğlu’nda eşyalı kiralık daire','Köroğlu','Daire',18500,70,'1+1',7598375],
 ['Bolu Merkez’de geniş kiralık daire','Bolu Merkez','Daire',28000,145,'3+1',35705942],
 ['Yeniçağa’da geleceğe yer açın','Yeniçağa','Arsa',1750000,650,'—',7939076],
 ['Göynük’te doğa manzaralı arsa','Göynük','Arsa',2400000,920,'—',15747270],
 ['Bolu Merkez’de cadde üzeri iş yeri','Bolu Merkez','İş Yeri',7500000,180,'2+0',4185944],
 ['Gerede’de kiralık ticari alan','Gerede','İş Yeri',32000,125,'1+0',31247732],
 ['Mengen’de geniş tarım arazisi','Mengen','Tarla',3200000,4800,'—',14515679],
];
export const properties:Property[]=seeds.map((s,i)=>({id:`MV-${1001+i}`,slug:slugify(s[0]),title:s[0],neighborhood:s[1],district:['Gerede','Mengen','Mudurnu','Göynük','Yeniçağa','Dörtdivan'].includes(s[1])?s[1]:'Merkez',propertyType:s[2],price:s[3],grossArea:s[4],netArea:Math.round(s[4]*.86),rooms:s[5],transactionType:[2,11,12,16].includes(i)?'Kiralık':'Satılık',currency:'TRY',city:'Bolu',address:`${s[1]}, Bolu · Temsili konum`,buildingAge:i%8,floor:s[2]==='Daire'?String(i%4+1):'Müstakil',totalFloors:5,heating:['Arsa','Tarla'].includes(s[2])?'Yok':i%3===0?'Yerden ısıtma':'Doğalgaz kombi',bathrooms:['Arsa','Tarla'].includes(s[2])?0:s[4]>140?2:1,balcony:s[2]==='Daire'||s[2]==='Villa',parking:i%3!==1,elevator:s[2]==='Daire'&&i%3!==0,furnished:i===11,creditEligible:![2,11,12,16,17].includes(i),inComplex:i%3===0,latitude:40.735+i*.002,longitude:31.598+(i%6)*.008,description:`${s[1]} bölgesindeki bu ${s[2].toLocaleLowerCase('tr')}, ${s[4]} m² brüt alanıyla farklı yaşam ve yatırım ihtiyaçları için sunulmuştur. ${['Arsa','Tarla'].includes(s[2])?'Doğayla çevrili konumu ve geniş yüzölçümü, uzun vadeli planlar için bir başlangıç olabilir. İmar, tapu ve ulaşım bilgileri gerçek bir işlem öncesinde ilgili kurumdan doğrulanmalıdır.':'Dengeli oda yerleşimi ve gün ışığını içeri alan açıklıkları, mekânı işlevsel kılar. Günlük ihtiyaçlara erişim ve çevreyle kurduğu ilişki, bu portföyün öne çıkan özellikleridir.'} Bu ilan kurgusal demo içeriğidir; fiyatlar, özellikler, konum ve stok fotoğrafları gerçek bir satış teklifini temsil etmez.`,features:['Açık manzara','Ulaşımı kolay',...(i%3===0?['Site içinde','Güvenlik']:[])],images:[photo(s[6]),photo(s[6],1600)],advisorId:`a${i%3+1}`,featured:i<6,createdAt:`2026-09-${String(8-i%8).padStart(2,'0')}`,status:'Aktif',isDemo:true}));
export const companyInfo={name:'Mavi Gayrimenkul',location:'Bolu Merkez / Bolu',email:'merhaba@mavi.example',phone:'Demo iletişim',isDemo:true,credit:'MK Digital Systems tarafından geliştirilen portföy çalışması.'};
export const statistics=[{value:'18',label:'Seçili portföy'},{value:'14',label:'Satılık gayrimenkul'},{value:'4',label:'Kiralık gayrimenkul'},{value:'12',label:'Bölgeyi keşfedin'}];
export const advisors=[{id:'a1',slug:'deniz-yilmaz',name:'Deniz Yılmaz',initials:'DY',specialty:'Konut & yaşam alanları',region:'Bolu Merkez · Bahçelievler',color:'#dce6e6',bio:'Bir evin değerini yalnızca metrekaresinde aramayan Deniz, ihtiyaçları dinleyerek başlayan bir danışmanlık yaklaşımını temsil ediyor. Konut seçimi, portföy sunumu ve gösterim planlaması uzmanlık alanları.',image:''},{id:'a2',slug:'emre-kaya',name:'Emre Kaya',initials:'EK',specialty:'Villa & arsa yatırımları',region:'Karacasu · Mudurnu · Mengen',color:'#e6e1d7',bio:'Emre’nin odağı, doğaya yakın yaşam alanları ve uzun vadeli gayrimenkul planları. Bölge, mülk özellikleri ve kullanım beklentilerini aynı masada değerlendiriyor.',image:''},{id:'a3',slug:'selin-demir',name:'Selin Demir',initials:'SD',specialty:'Kiralama & ticari gayrimenkul',region:'Bolu Merkez · Gerede',color:'#e3e6ef',bio:'Selin, kiralık konut ve ticari alan arayışını net bir ihtiyaç listesiyle ele alıyor. Mülk sahipleri ve kiracı adayları arasında açık, düzenli bir iletişim deneyimini temsil ediyor.',image:''}];
export const regions=locations.filter(x=>!['Köroğlu','Göynük','Yeniçağa','Dörtdivan'].includes(x)).map((name,i)=>({name,slug:slugify(name),image:photo([7598364,7587877,12029111,4185944,7598375,37140648,35705942,31247732,26812642,7885520,15747270,14515679][i]),lifestyle:i%3===0?'Şehrin ritmine yakın':i%3===1?'Doğayla dengeli bir yaşam':'Günlük hayata daha fazla alan',description:`${name}; ${i%3===0?'merkezi yaşamı ve farklı konut seçenekleriyle':i%3===1?'yeşil çevresi ve sakin yaşam beklentisiyle':'aile yaşamına uygun alternatifleri ve mahalle dokusuyla'} keşfedilmeyi bekliyor. Size uygun yaşamı, bölgenin sunduklarıyla birlikte düşünelim.`,trend:'Piyasa verisi bağlı değil'}));
export const blogPosts=[
 {slug:'boluda-ev-almak',title:'Bolu’da ev arayışına nereden başlamalı?',category:'YAŞAM REHBERİ',image:photo(7598364),intro:'Bir ev seçmek, günlük hayatınızın nasıl akacağını seçmektir.',sections:[['Önce yaşamınızı düşünün','İşe gidiş süreniz, açık alan ihtiyacınız ve yakın olmak istediğiniz yerler, ev arayışının başlangıç noktası olabilir. Önceliklerinizi üç vazgeçilmez ve üç esnek tercih olarak listeleyin.'],['Mekânı farklı saatlerde görün','Gün ışığını, çevrenin hareketliliğini ve odaların gerçek kullanımını bir ziyaretle değerlendirmek zordur. İkinci bir gösterim, ilk izleniminizi somut hale getirir.'],['Sorularınızı yazılı tutun','Brüt ve net alan, bakım ihtiyacı ve ortak alanlar hakkında sorularınızı danışmanınıza iletin.']]},
 {slug:'bolu-bolge-rehberi',title:'Şehrin içinde mi, doğanın yanında mı?',category:'BÖLGE NOTLARI',image:photo(7885520),intro:'Bolu’da yaşam beklentinize uygun çevreyi keşfedin.',sections:[['Günlük rotanız belirleyici','Merkezde yaşamak kısa günlük rotalar sunabilir. Daha sakin bir çevre arayışında ise ulaşım alışkanlıklarını ve hizmetlere mesafeyi birlikte düşünün.'],['Beklentileri karşılaştırın','Bahçe, manzara ve geniş alan ihtiyacınızla günlük bakım sorumluluğunu birlikte değerlendirin. Bölge sayfalarımız temsili olup gerçek fiyat trendi içermez.']]},
 {slug:'arsa-kontrol-listesi',title:'Arsa arayışınız için bir soru listesi',category:'GAYRİMENKUL NOTLARI',image:photo(7939076),intro:'Doğru sorular, bilinçli bir görüşmenin ilk adımıdır.',sections:[['Kullanım amacınızı netleştirin','Bir yaşam alanı kurmak mı, tarımsal kullanım mı düşünüyorsunuz? Beklentiniz, incelemeniz gereken mülk tipini belirler.'],['Belgeleri uzmanıyla değerlendirin','Tapu, imar, sınırlar ve erişim gibi konuları yetkili kurumlar ve ilgili uzmanlarla doğrulayın. İlandaki bir açıklama resmi incelemenin yerini tutmaz.']]},
 {slug:'daire-degerleme',title:'Bir evin değerini oluşturan detaylar',category:'MÜLK SAHİPLERİ İÇİN',image:photo(15251055),intro:'Metrekarenin ötesinde, bir bütünü değerlendirmek.',sections:[['Benzer olan her ev aynı değildir','Konum, kat, gün ışığı, bakım durumu ve kullanım planı bir evin değerlendirilmesinde birlikte ele alınabilir.'],['Yerinde inceleme ile başlayın','Fotoğraf ve bilgiler bir başlangıç sunar. Bu demodaki değerleme formu talep deneyimini gösterir; otomatik fiyat tahmini üretmez.']]},
 {slug:'ev-kiralama',title:'Yeni evinize taşınmadan önce',category:'KİRALAMA REHBERİ',image:photo(19889118),intro:'Daha rahat bir taşınma için küçük bir hazırlık.',sections:[['İhtiyaçlarınızı sıraya koyun','Eşyalı veya eşyasız seçenekleri, oda ihtiyacınızı ve ulaşım beklentinizi listeleyin. Kira dışındaki düzenli giderleri de bütçenizde düşünün.'],['Evi birlikte gezin','Mevcut donanımları ve kullanım durumunu yerinde inceleyin. Sözleşme ve yükümlülükler hakkında gerektiğinde yetkin bir uzmandan görüş alın.']]},
];
export const testimonials=[{name:'Ayşe K.',text:'Aradığımız evin nasıl olması gerektiğini birlikte netleştirdik. En güzel yanı, gerçekten dinlendiğimizi hissetmekti.',type:'Konut arayışı'},{name:'Mert A.',text:'Her portföyün artılarını ve dikkat etmemiz gereken noktalarını aynı açıklıkla görmek karar vermeyi kolaylaştırdı.',type:'Mülk seçimi'},{name:'Elif T.',text:'Mülkümüzü sunma biçimi ve düzenli bilgilendirme, beklediğimiz danışmanlık deneyimiydi.',type:'Mülk sahibi'}];
export const money=(n:number)=>new Intl.NumberFormat('tr-TR').format(n)+' ₺';
