import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {Suspense} from 'react';
import {properties,regions,advisors,blogPosts} from '@/lib/data';
import {Listings} from '@/components/listings';
import {PropertyDetail} from '@/components/property-detail';
import {Comparison} from '@/components/comparison';
import {RegionsPage,AdvisorsPage,BlogPage,AboutPage,FormPage,ProjectsPage} from '@/components/content-pages';
const titles:Record<string,string>={satilik:'Satılık Portföyler',kiralik:'Kiralık Portföyler',favoriler:'Favorilerim',karsilastir:'Portföy Karşılaştırma',bolgeler:'Bolu Bölge Rehberi',danismanlar:'Danışmanlarımız','yatirim-rehberi':'Yatırım ve Yaşam Rehberi',hakkimizda:'Mavi’nin Yaklaşımı',degerleme:'Ücretsiz Değerleme','portfoy-gonder':'Portföyünü Gönder',iletisim:'İletişim',projeler:'Yaşam Projeleri'};
export function generateStaticParams(){return [...Object.keys(titles).map(s=>({slug:[s]})),...properties.map(p=>({slug:['ilan',p.slug]})),...regions.map(r=>({slug:['bolgeler',r.slug]})),...advisors.map(a=>({slug:['danismanlar',a.slug]})),...blogPosts.map(b=>({slug:['yatirim-rehberi',b.slug]}))]}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const p=slug[0]==='ilan'?properties.find(p=>p.slug===slug[1]):undefined;const title=p?.title||(slug[0]==='bolgeler'?regions.find(x=>x.slug===slug[1])?.name:slug[0]==='danismanlar'?advisors.find(x=>x.slug===slug[1])?.name:slug[0]==='yatirim-rehberi'?blogPosts.find(x=>x.slug===slug[1])?.title:undefined)||titles[slug[0]]||'Sayfa bulunamadı';const description=p?`${p.neighborhood}, Bolu · ${p.grossArea} m² · ${p.rooms} · ${p.transactionType}. Kurgusal demo ilanı, fotoğraflar temsilidir.`:`${title} · Mavi Gayrimenkul, MK Digital Systems demo çalışması.`;return{title,description,alternates:{canonical:`/${slug.join('/')}`},openGraph:{title,description,type:'website'}}}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const{slug}=await params;const [route,id]=slug;if(slug.length>2)notFound();if(route==='ilan'){const p=properties.find(p=>p.slug===id);if(!p)notFound();return <PropertyDetail property={p}/>};if(['satilik','kiralik','favoriler'].includes(route)&&!id)return <Suspense fallback={<main id="main" className="container loading-page">Portföyler hazırlanıyor…</main>}><Listings mode={route}/></Suspense>;if(route==='karsilastir'&&!id)return <Comparison/>;if(route==='bolgeler'){if(id&&!regions.some(x=>x.slug===id))notFound();return <RegionsPage slug={id}/>};if(route==='danismanlar'){if(id&&!advisors.some(x=>x.slug===id))notFound();return <AdvisorsPage slug={id}/>};if(route==='yatirim-rehberi'){if(id&&!blogPosts.some(x=>x.slug===id))notFound();return <BlogPage slug={id}/>};if(id)notFound();if(route==='hakkimizda')return <AboutPage/>;if(route==='projeler')return <ProjectsPage/>;if(route==='degerleme'||route==='iletisim'||route==='portfoy-gonder')return <FormPage kind={route==='portfoy-gonder'?'portfoy':route}/>;notFound()}
